
package introsde.project.business.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import introsde.project.adopter.recombee.soap.Evaluation;
import introsde.project.adopter.recombee.soap.ItemObject;
import introsde.project.adopter.recombee.soap.RecombeeDBType;
import introsde.project.data.local.soap.FoodType;
import introsde.project.data.local.soap.MovieGen;
import introsde.project.data.local.soap.Person;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BusinessInterface", targetNamespace = "http://soap.business.project.introsde/")
@XmlSeeAlso({
    introsde.project.adopter.recombee.soap.ObjectFactory.class,
    introsde.project.business.soap.ObjectFactory.class,
    introsde.project.data.local.soap.ObjectFactory.class
})
public interface BusinessInterface {


    /**
     * 
     * @param username
     * @return
     *     returns introsde.project.data.local.soap.Person
     */
    @WebMethod
    @WebResult(name = "Person", targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetUserResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/getUserRequest", output = "http://soap.business.project.introsde/BusinessInterface/getUserResponse")
    public Person getUser(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param person
     * @return
     *     returns introsde.project.data.local.soap.Person
     */
    @WebMethod
    @WebResult(name = "Person", targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.UpdateUserResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/updateUserRequest", output = "http://soap.business.project.introsde/BusinessInterface/updateUserResponse")
    public Person updateUser(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.project.data.local.soap.Person>
     */
    @WebMethod
    @WebResult(name = "PersonList", targetNamespace = "")
    @RequestWrapper(localName = "getAllUser", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetAllUser")
    @ResponseWrapper(localName = "getAllUserResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetAllUserResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/getAllUserRequest", output = "http://soap.business.project.introsde/BusinessInterface/getAllUserResponse")
    public List<Person> getAllUser();

    /**
     * 
     * @param itemName
     * @param dbName
     * @return
     *     returns java.util.List<introsde.project.adopter.recombee.soap.ItemObject>
     */
    @WebMethod
    @WebResult(name = "ListofStrings", targetNamespace = "")
    @RequestWrapper(localName = "getItemsByType", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetItemsByType")
    @ResponseWrapper(localName = "getItemsByTypeResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetItemsByTypeResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/getItemsByTypeRequest", output = "http://soap.business.project.introsde/BusinessInterface/getItemsByTypeResponse")
    public List<ItemObject> getItemsByType(
        @WebParam(name = "dbName", targetNamespace = "")
        RecombeeDBType dbName,
        @WebParam(name = "itemName", targetNamespace = "")
        String itemName);

    /**
     * 
     * @param quantity
     * @param person
     * @param dbName
     * @return
     *     returns java.util.List<introsde.project.adopter.recombee.soap.ItemObject>
     */
    @WebMethod
    @WebResult(name = "recommendations", targetNamespace = "")
    @RequestWrapper(localName = "getRecommendations", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetRecommendations")
    @ResponseWrapper(localName = "getRecommendationsResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetRecommendationsResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/getRecommendationsRequest", output = "http://soap.business.project.introsde/BusinessInterface/getRecommendationsResponse")
    public List<ItemObject> getRecommendations(
        @WebParam(name = "dbName", targetNamespace = "")
        RecombeeDBType dbName,
        @WebParam(name = "person", targetNamespace = "")
        Person person,
        @WebParam(name = "quantity", targetNamespace = "")
        int quantity);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.project.data.local.soap.FoodType>
     */
    @WebMethod
    @WebResult(name = "FoodTypeList", targetNamespace = "")
    @RequestWrapper(localName = "getFoodTypes", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetFoodTypes")
    @ResponseWrapper(localName = "getFoodTypesResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetFoodTypesResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/getFoodTypesRequest", output = "http://soap.business.project.introsde/BusinessInterface/getFoodTypesResponse")
    public List<FoodType> getFoodTypes();

    /**
     * 
     * @return
     *     returns java.util.List<introsde.project.data.local.soap.MovieGen>
     */
    @WebMethod
    @WebResult(name = "MovieGenList", targetNamespace = "")
    @RequestWrapper(localName = "getMovieGens", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetMovieGens")
    @ResponseWrapper(localName = "getMovieGensResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetMovieGensResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/getMovieGensRequest", output = "http://soap.business.project.introsde/BusinessInterface/getMovieGensResponse")
    public List<MovieGen> getMovieGens();

    /**
     * 
     * @param dbName
     * @param rating
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "boolean", targetNamespace = "")
    @RequestWrapper(localName = "modifyRating", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.ModifyRating")
    @ResponseWrapper(localName = "modifyRatingResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.ModifyRatingResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/modifyRatingRequest", output = "http://soap.business.project.introsde/BusinessInterface/modifyRatingResponse")
    public boolean modifyRating(
        @WebParam(name = "dbName", targetNamespace = "")
        RecombeeDBType dbName,
        @WebParam(name = "rating", targetNamespace = "")
        Evaluation rating);

    /**
     * 
     * @param itemName
     * @param dbName
     * @return
     *     returns java.util.List<introsde.project.adopter.recombee.soap.Evaluation>
     */
    @WebMethod
    @WebResult(name = "ratingList", targetNamespace = "")
    @RequestWrapper(localName = "getItemRatings", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetItemRatings")
    @ResponseWrapper(localName = "getItemRatingsResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetItemRatingsResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/getItemRatingsRequest", output = "http://soap.business.project.introsde/BusinessInterface/getItemRatingsResponse")
    public List<Evaluation> getItemRatings(
        @WebParam(name = "dbName", targetNamespace = "")
        RecombeeDBType dbName,
        @WebParam(name = "itemName", targetNamespace = "")
        String itemName);

    /**
     * 
     * @param person
     * @param dbName
     * @return
     *     returns java.util.List<introsde.project.adopter.recombee.soap.Evaluation>
     */
    @WebMethod
    @WebResult(name = "ratingList", targetNamespace = "")
    @RequestWrapper(localName = "getUserRatings", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetUserRatings")
    @ResponseWrapper(localName = "getUserRatingsResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetUserRatingsResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/getUserRatingsRequest", output = "http://soap.business.project.introsde/BusinessInterface/getUserRatingsResponse")
    public List<Evaluation> getUserRatings(
        @WebParam(name = "dbName", targetNamespace = "")
        RecombeeDBType dbName,
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param token
     * @return
     *     returns introsde.project.data.local.soap.Person
     */
    @WebMethod
    @WebResult(name = "Person", targetNamespace = "")
    @RequestWrapper(localName = "getPersonByToken", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetPersonByToken")
    @ResponseWrapper(localName = "getPersonByTokenResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetPersonByTokenResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/getPersonByTokenRequest", output = "http://soap.business.project.introsde/BusinessInterface/getPersonByTokenResponse")
    public Person getPersonByToken(
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param itemName
     * @param itemType
     * @param dbName
     * @param location
     * @return
     *     returns introsde.project.adopter.recombee.soap.ItemObject
     */
    @WebMethod
    @WebResult(name = "StringId", targetNamespace = "")
    @RequestWrapper(localName = "addNewItem", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.AddNewItem")
    @ResponseWrapper(localName = "addNewItemResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.AddNewItemResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/addNewItemRequest", output = "http://soap.business.project.introsde/BusinessInterface/addNewItemResponse")
    public ItemObject addNewItem(
        @WebParam(name = "dbName", targetNamespace = "")
        RecombeeDBType dbName,
        @WebParam(name = "itemName", targetNamespace = "")
        String itemName,
        @WebParam(name = "itemType", targetNamespace = "")
        String itemType,
        @WebParam(name = "location", targetNamespace = "")
        String location);

    /**
     * 
     * @param dbName
     * @param rating
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "boolean", targetNamespace = "")
    @RequestWrapper(localName = "addNewRating", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.AddNewRating")
    @ResponseWrapper(localName = "addNewRatingResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.AddNewRatingResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/addNewRatingRequest", output = "http://soap.business.project.introsde/BusinessInterface/addNewRatingResponse")
    public boolean addNewRating(
        @WebParam(name = "dbName", targetNamespace = "")
        RecombeeDBType dbName,
        @WebParam(name = "rating", targetNamespace = "")
        Evaluation rating);

    /**
     * 
     * @param dbName
     * @return
     *     returns java.util.List<introsde.project.adopter.recombee.soap.ItemObject>
     */
    @WebMethod
    @WebResult(name = "ListofStrings", targetNamespace = "")
    @RequestWrapper(localName = "getAllItem", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetAllItem")
    @ResponseWrapper(localName = "getAllItemResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetAllItemResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/getAllItemRequest", output = "http://soap.business.project.introsde/BusinessInterface/getAllItemResponse")
    public List<ItemObject> getAllItem(
        @WebParam(name = "dbName", targetNamespace = "")
        RecombeeDBType dbName);

    /**
     * 
     * @param person
     * @return
     *     returns introsde.project.data.local.soap.Person
     */
    @WebMethod
    @WebResult(name = "Person", targetNamespace = "")
    @RequestWrapper(localName = "addNewUser", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.AddNewUser")
    @ResponseWrapper(localName = "addNewUserResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.AddNewUserResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/addNewUserRequest", output = "http://soap.business.project.introsde/BusinessInterface/addNewUserResponse")
    public Person addNewUser(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param itemName
     * @param dbName
     * @return
     *     returns introsde.project.adopter.recombee.soap.ItemObject
     */
    @WebMethod
    @WebResult(name = "ItemObject", targetNamespace = "")
    @RequestWrapper(localName = "getItem", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://soap.business.project.introsde/", className = "introsde.project.business.soap.GetItemResponse")
    @Action(input = "http://soap.business.project.introsde/BusinessInterface/getItemRequest", output = "http://soap.business.project.introsde/BusinessInterface/getItemResponse")
    public ItemObject getItem(
        @WebParam(name = "dbName", targetNamespace = "")
        RecombeeDBType dbName,
        @WebParam(name = "itemName", targetNamespace = "")
        String itemName);

}
