
package introsde.project.business.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BusinessImplService", targetNamespace = "http://soap.business.project.introsde/", wsdlLocation = "http://business-introsde-2018.herokuapp.com/ws/business?wsdl")
public class BusinessImplService
    extends Service
{

    private final static URL BUSINESSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BUSINESSIMPLSERVICE_EXCEPTION;
    private final static QName BUSINESSIMPLSERVICE_QNAME = new QName("http://soap.business.project.introsde/", "BusinessImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://business-introsde-2018.herokuapp.com/ws/business?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUSINESSIMPLSERVICE_WSDL_LOCATION = url;
        BUSINESSIMPLSERVICE_EXCEPTION = e;
    }

    public BusinessImplService() {
        super(__getWsdlLocation(), BUSINESSIMPLSERVICE_QNAME);
    }

    public BusinessImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BUSINESSIMPLSERVICE_QNAME, features);
    }

    public BusinessImplService(URL wsdlLocation) {
        super(wsdlLocation, BUSINESSIMPLSERVICE_QNAME);
    }

    public BusinessImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BUSINESSIMPLSERVICE_QNAME, features);
    }

    public BusinessImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BusinessImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BusinessInterface
     */
    @WebEndpoint(name = "BusinessImplPort")
    public BusinessInterface getBusinessImplPort() {
        return super.getPort(new QName("http://soap.business.project.introsde/", "BusinessImplPort"), BusinessInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BusinessInterface
     */
    @WebEndpoint(name = "BusinessImplPort")
    public BusinessInterface getBusinessImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.business.project.introsde/", "BusinessImplPort"), BusinessInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUSINESSIMPLSERVICE_EXCEPTION!= null) {
            throw BUSINESSIMPLSERVICE_EXCEPTION;
        }
        return BUSINESSIMPLSERVICE_WSDL_LOCATION;
    }

}
